# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: "多語歐拉瑪項目實作 -- Ollama Polyglot Project" # Website name
baseURL: 'https://oxfordroadmap.github.io/documentation' # Website URL
canonifyURLs: 'false'

############################
## PAGE OPTIONS
############################

cascade:
  # Docs folder options
  - _target:
      path: /docs/**
    editable: true
    show_breadcrumb: true
    # Hide date from Next In Series
    show_date: false
    # Show date modified at end of content
    show_date_updated: true
  # Blog post options
  - _target:
      path: /post/**
      kind: page
    pager: true
    editable: true
    hide_date: false
    show_date_updated: true
    reading_time: true
    commentable: true
    show_related: true
    share: true
    # Just use Breadcrumb for navigation on blog post pages?
    show_breadcrumb: true
    header:
      navbar:
        enable: true

############################
## LANGUAGE
############################

defaultContentLanguage: zh-hant
defaultContentLanguageInSubdir: false
hasCJKLanguage: true
removePathAccents: true
languages:
  zh-hant:
    disabled: false
    languageCode: zh-hant
    languageName: 中文 (正體)
    languageDirection: ltr
    title: 多語歐拉瑪項目實作 
    disabled: false
    weight: 1
  en:
    disabled: false
    languageCode: en-US
    languageName: English
    languageDirection: ltr
    title: Ollama Polyglot Project
    weight: 2

############################
## ADVANCED
############################

enableGitInfo: true
summaryLength: 30
pagination:
  pagerSize: 10
enableRobotsTXT: true
build:
  writeStats: true
enableGitInfo: false
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
enableInlineShortcodes: true
permalinks:
  authors: '/author/:slug/'
  tags: '/tag/:slug/'
  categories: '/category/:slug/'
disableAliases: true
outputs:
  home: [HTML, RSS, WebAppManifest, headers, redirects, backlinks]
  page: [HTML]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 85
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
markup:
  _merge: deep
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: true 
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
minify:
  _merge: deep
refLinksErrorLevel: WARNIx